#!/bin/sh
#
# CUSTOMIZE THIS to however/wherever you installed:
#                  - numerous.py library (usually ~/lib)
#                    (or unnecessary if you installed in system library via pip)
#                  - nr.py python shell-level command (usually ~/bin)
#                  

# uncomment this and set appropriately if you did not install using pip
# PYTHONPATH=$HOME/lib ; export PYTHONPATH

# you might need to edit this depending on where you installed nr and nr.py
$HOME/bin/nr.py "$@"
